// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LZO87tB4ODbDTWyAJ-m8Lz1whmrDvMw',
    appId: '1:146990742626:web:4db220a56d2f8a5aaf253b',
    messagingSenderId: '146990742626',
    projectId: 'fir-cb1ed',
    authDomain: 'fir-cb1ed.firebaseapp.com',
    storageBucket: 'fir-cb1ed.appspot.com',
    measurementId: 'G-R4WD23TCEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3kVeQHVWM4YFu0568QdTceC35tyFWjsM',
    appId: '1:146990742626:android:a97e0d5f23e26eeeaf253b',
    messagingSenderId: '146990742626',
    projectId: 'fir-cb1ed',
    storageBucket: 'fir-cb1ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWAierUwrVhwkNnJSEP67HS7B7SlFeeC4',
    appId: '1:146990742626:ios:360c1dbeb6d5e906af253b',
    messagingSenderId: '146990742626',
    projectId: 'fir-cb1ed',
    storageBucket: 'fir-cb1ed.appspot.com',
    iosClientId: '146990742626-rfrpat56pql9vpj2hirravqmg3hnfj2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vacApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWAierUwrVhwkNnJSEP67HS7B7SlFeeC4',
    appId: '1:146990742626:ios:360c1dbeb6d5e906af253b',
    messagingSenderId: '146990742626',
    projectId: 'fir-cb1ed',
    storageBucket: 'fir-cb1ed.appspot.com',
    iosClientId: '146990742626-rfrpat56pql9vpj2hirravqmg3hnfj2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vacApp',
  );
}
